# Generated by Django 5.0.6 on 2025-03-29 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QoSInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_strength', models.FloatField()),
                ('required_bandwidth', models.FloatField()),
                ('allocated_bandwidth', models.FloatField()),
                ('resource_allocation', models.FloatField()),
                ('cpu_utilization', models.FloatField()),
                ('memory_utilization', models.FloatField()),
                ('distance_from_bs', models.FloatField()),
                ('slice_type', models.CharField(choices=[('URLLC', 'URLLC'), ('eMBB', 'eMBB')], max_length=10)),
                ('application_type', models.CharField(choices=[('Background_Download', 'Background Download'), ('Emergency_Service', 'Emergency Service'), ('File_Download', 'File Download'), ('IoT_Temperature', 'IoT Temperature'), ('Online_Gaming', 'Online Gaming'), ('Streaming', 'Streaming'), ('Video_Call', 'Video Call'), ('Video_Streaming', 'Video Streaming'), ('VoIP_Call', 'VoIP Call'), ('Voice_Call', 'Voice Call'), ('Web_Browsing', 'Web Browsing')], max_length=30)),
                ('slice_priority', models.CharField(choices=[('High', 'High'), ('Low', 'Low')], max_length=10)),
                ('time_of_day', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening')], max_length=10)),
                ('weather_conditions', models.CharField(choices=[('Cloudy', 'Cloudy'), ('Rainy', 'Rainy'), ('Sunny', 'Sunny')], max_length=10)),
                ('user_mobility', models.CharField(choices=[('Driving', 'Driving'), ('Stationary', 'Stationary'), ('Walking', 'Walking')], max_length=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QoSPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latency', models.FloatField()),
                ('jitter', models.FloatField()),
                ('throughput', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('input_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='predictor.qosinput')),
            ],
        ),
    ]
